
[general]
	#The material blacklist of this module.
	materialBlacklist = ["Abyssalnite", "AirElemental", "Amber", "Ardite", "ChargedCertusQuartz", "Coralium", "Dark", "DimensionalShard", "EarthElemental", "Elemental", "FireElemental", "WaterElemental", "Zanite", "Resonating", "AurorianGeode", "AurorianCoal", "Ambrosium", "Aether"]

