
[general]
#The material blacklist of this module.
materialBlacklist = [
	"Abyssalnite",
	"AirElemental",
	"Amber",
	"CertusQuartz",
	"ChargedCertusQuartz",
	"Coralium",
	"Dark",
	"Dilithium",
	"DimensionalShard",
	"EarthElemental",
	"Elemental",
	"FireElemental",
	"Mithril",
	"QuartzBlack",
	"WaterElemental",
]
#The materials to force generate passive forms for this module.
passiveMaterialWhitelist = []
