
[general]
	#The material blacklist of this module.
	materialBlacklist = ["Abyssalnite", "Aluminum", "Ardite", "Boron", "Cobalt", "Iridium", "LiquifiedCoralium", "Lithium", "Magnesium", "Mithril", "Nickel", "Platinum", "Thorium", "Titanium", "Uranium", "Cerulean", "Moonstone"]

