import com.dimensional.gatewaycore.events.TooltipEvents

TooltipEvents.setTierName(1, "Beginnings")
TooltipEvents.setTierName(2, "Temple Run")
TooltipEvents.setTierName(3, "Metallurgy")
TooltipEvents.setTierName(4, "The Evil Arc")
TooltipEvents.setTierName(5, "Basics of Magic")
TooltipEvents.setTierName(6, "Sky Exploration")
TooltipEvents.setTierName(7, "Electrical Engineering")
TooltipEvents.setTierName(8, "Chemical Mayhem")
TooltipEvents.setTierName(9, "Botanical Basics")
TooltipEvents.setTierName(10, "Bloody Empowering")
TooltipEvents.setTierName(11, "Industrial Revolution")
TooltipEvents.setTierName(12, "Magic Advancements")
TooltipEvents.setTierName(13, "Particle Mastery")
TooltipEvents.setTierName(14, "Demonic Embrace")
TooltipEvents.setTierName(15, "Beyond Creativity")
TooltipEvents.setTierName(16, "The Gateway")
