import com.dimensional.gatewaycore.events.TooltipEvents

TooltipEvents.setTierName(1, "Beginnings")
TooltipEvents.setTierName(2, "Temple Run")
TooltipEvents.setTierName(3, "Metallurgy")
TooltipEvents.setTierName(4, "The Evil Arc")
TooltipEvents.setTierName(5, "Basics of Magic")
TooltipEvents.setTierName(6, "Sky Exploration")
TooltipEvents.setTierName(7, "Cosmic Engineering")
TooltipEvents.setTierName(8, "Automation")
TooltipEvents.setTierName(9, "Botanical Basics")
TooltipEvents.setTierName(10, "Empowering")
TooltipEvents.setTierName(11, "Industrial Revolution")
TooltipEvents.setTierName(12, "Magic Advancements")
TooltipEvents.setTierName(13, "Particle Manipulation")
TooltipEvents.setTierName(14, "Elven Absolution")
TooltipEvents.setTierName(15, "Demonic Embrace")
TooltipEvents.setTierName(16, "Dragon Variation")
TooltipEvents.setTierName(17, "Beyond Creativity")
TooltipEvents.setTierName(18, "The End")
