// Storage Upgrades
crafting.remove("storagedrawers:upgrade_storage_diamond")
crafting.remove("storagedrawers:upgrade_storage_emerald")
crafting.shapedBuilder()
        .name("tier4/drawer/upgrade_t4")
        .output(item("storagedrawers:upgrade_storage", 3))
        .matrix("G", "T", "G")
        .key("G", item("essentialcraft:genitem", 44)).key("T", item("storagedrawers:upgrade_storage", 2))
        .register()
crafting.shapedBuilder()
        .name("tier4/drawer/upgrade_t5")
        .output(item("storagedrawers:upgrade_storage", 4))
        .matrix("G", "T", "G")
        .key("G", item("essentialcraft:genitem", 40)).key("T", item("storagedrawers:upgrade_storage", 3))
        .register()
