
#Configurations related to materials.
[materials]
	#Should the mod find ingot materials with ores.
	ingot = true
	#Should the mod find gem materials with ores.
	gem = true
	#Should the mod find crystal materials with ores.
	crystal = false
	#Should the mod find dust materials with ores.
	dust = true
	#Should the mod find ingot materials without ores.
	ingotPlain = false
	#Should the mod find gem materials without ores.
	gemPlain = false
	#Should the mod find crystal materials without ores.
	crystalPlain = false
	#Should the mod find dust materials without ores.
	dustPlain = false
	#Should the mod not find materials with ores with used prefixes.
	nonPlainUsedPrefix = false
	#Should the mod not find materials with used prefixes when the material name is not found yet.
	strictUsedPrefix = false

#Configurations related to material overrides.
[materialOverrides]
	#List of materials that should be gems.
	gem = ["Coal", "Diamond", "Emerald", "Lapis", "Prismarine", "Quartz"]
	#List of materials that should be crystals.
	crystal = []
	#List of materials that should be dusts.
	dust = ["Redstone"]

#Configurations related to item selection.
[itemSelection]
	#List of mods that are preferred when selecting items in recipes.
	preferredMods = ["minecraft", "jaopca"]

#Configurations related to the ore dictionary.
[oredict]
	#List of oredict names that should not be added.
	blacklist = []
	#List of oredict modules that should not be registered.
	moduleBlacklist = []
	#List of custom oredict entries to add. Format: <mod:item@meta=oredict>
	custom = ["aether_legacy:zanite_ore=oreZanite", "aether_legacy:zanite_gemstone=gemZanite", "aether_legacy:zanite_block=blockZanite", "aether_legacy:ambrosium_ore=oreAmbrosium", "aether_legacy:ambrosium_shard=gemAmbrosium", "deepresonance:resonating_ore@2=oreResonating", "deepresonance:resonating_plate=dustResonating", "aetherworks:aether_ore=oreAether", "aetherworks:item_resource@5=gemAether", "theaurorian:auroriancoalore=oreAurorianCoal", "theaurorian:auroriancoal=gemAurorianCoal", "theaurorian:auroriancoalblock=blockAurorianCoal", "theaurorian:ceruleanore=oreCerulean", "theaurorian:ceruleaningot=ingotCerulean", "theaurorian:ceruleanblock=blockCerulean", "theaurorian:geodeore=oreAurorianGeode", "theaurorian:crystal=gemAurorianGeode", "theaurorian:moonstoneore=oreMoonstone", "theaurorian:moonstoneingot=ingotMoonstone", "theaurorian:moonstoneblock=blockMoonstone"]

#Configurations related to recipes.
[recipes]
	#List of recipes that should not be added.
	blacklist = []
	#List of recipes by regex that should not be added.
	regexBlacklist = [".*"]

#Configurations related to color generation.
[colors]
	#The gamma value used to blend colors.
	gammaValue = 2.0
	#Should colors of all materials be reset on next startup.
	resetColors = false

#Configurations related to material localization.
[materialLocalization]
	#Should the mod check for material localization updates.
	checkL10nUpdates = true
	#The update interval of localization files in days.
	updateInterval = 3.0

