// Thaum infused tools
mods.thaumcraft.infusion_crafting.removeByOutput(item("thaumcraft:elemental_pick"))
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("BRR")
    .row(" M ")
    .row(" H ")
    .key("M", item("thaumcraft:thaumium_pick"))
    .key("R", item("actuallyadditions:item_crystal", 2))
    .key("H", item("essentialcraft:genitem", 25))
    .key("B", item("essentialcraft:genitem", 79))
    .aspect("terra", 8)
    .aspect("ignis", 16)
    .vis(30)
    .output(item("thaumcraft:elemental_pick").withNbt(["infench":[["id":4,"lvl":1],["id":3,"lvl":2]]]))
    .register()

mods.thaumcraft.infusion_crafting.removeByOutput(item("thaumcraft:elemental_axe"))
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("BRW")
    .row("RM ")
    .row(" H ")
    .key("M", item("thaumcraft:thaumium_axe"))
    .key("R", item("actuallyadditions:item_crystal", 1))
    .key("H", item("natura:sticks", 10))
    .key("B", item("essentialcraft:genitem", 8))
    .key("W", item("essentialcraft:genitem", 6))
    .aspect("aer", 4)
    .aspect("aqua", 16)
    .aspect("ordo", 4)
    .vis(30)
    .output(item("thaumcraft:elemental_axe").withNbt(["infench":[["id":2,"lvl":1],["id":0,"lvl":1]]]))
    .register()

mods.thaumcraft.infusion_crafting.removeByOutput(item("thaumcraft:elemental_sword"))
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("R")
    .row("G")
    .row("M")
    .key("M", item("thaumcraft:thaumium_sword"))
    .key("R", item("actuallyadditions:item_crystal", 5))
    .key("G", item("essentialcraft:genitem", 9))
    .aspect("aer", 20)
    .aspect("ordo", 4)
    .vis(30)
    .output(item("thaumcraft:elemental_sword").withNbt(["infench":[["id":5,"lvl":2]]]))
    .register()

mods.thaumcraft.infusion_crafting.removeByOutput(item("thaumcraft:elemental_shovel"))
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("R")
    .row("M")
    .row("S")
    .key("M", item("thaumcraft:thaumium_shovel"))
    .key("R", item("actuallyadditions:item_crystal", 4))
    .key("S", item("natura:sticks", 11))
    .aspect("terra", 14)
    .aspect("perditio", 10)
    .vis(30)
    .output(item("thaumcraft:elemental_shovel").withNbt(["infench":[["id":1,"lvl":1]]]))
    .register()

mods.thaumcraft.infusion_crafting.removeByOutput(item("thaumcraft:elemental_hoe"))
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("RP")
    .row(" M")
    .row(" S")
    .key("M", item("thaumcraft:thaumium_shovel"))
    .key("R", item("actuallyadditions:item_crystal", 3))
    .key("P", item("essentialcraft:genitem", 39))
    .key("S", item("theaurorian:silentwoodstick"))
    .aspect("ordo", 12)
    .aspect("perditio", 12)
    .vis(30)
    .output(item("thaumcraft:elemental_hoe"))
    .register()

// EC4 Magical Porkchop (additional recipe before elemental)
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("CPC")
    .row("SMS")
    .row("HSH")
    .key("M", item("essentialcraft:storage", 3))
    .key("P", item("minecraft:porkchop"))
    .key("S", item("thaumcraft:fabric"))
    .key("C", item("minecraft:prismarine_crystals"))
    .key("H", item("minecraft:prismarine_shard"))
    .aspect("terra", 12)
    .aspect("aqua", 10)
    .aspect("ordo", 8)
    .vis(50)
    .output(item("essentialcraft:magicalporkchop"))
    .register()

// EC4 Magical Wings (additional recipe before elemental)
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("PWW")
    .row("PFF")
    .row("MFF")
    .key("F", item("roots:mystic_feather"))
    .key("M", item("essentialcraft:storage", 3))
    .key("P", ore("plateMagic"))
    .key("W", item("actuallyadditions:item_misc", 15))
    .aspect("aer", 20)
    .aspect("ignis", 10)
    .vis(50)
    .output(item("essentialcraft:magicalwings"))
    .register()
