// Wings of the Bats (switch to reliquary wing + cheaper)
crafting.remove("actuallyadditions:recipes43")
crafting.shapedBuilder()
    .name("equipment/actuallyadditions/wings")
    .matrix("WDW", "WEW", "WDW")
    .key("D", item("actuallyadditions:item_crystal_empowered", 2))
    .key("E", item("actuallyadditions:item_misc", 19))
    .key("W", item("xreliquary:mob_ingredient", 5))
    .output(item("actuallyadditions:item_wings_of_the_bats"))
    .register()
