// EC4 Magical Porkchop (additional recipe before elemental)
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("CPC")
    .row("SMS")
    .row("HSH")
    .key("M", item("essentialcraft:storage", 3))
    .key("P", item("minecraft:porkchop"))
    .key("S", item("thaumcraft:fabric"))
    .key("C", item("minecraft:prismarine_crystals"))
    .key("H", item("minecraft:prismarine_shard"))
    .aspect("terra", 12)
    .aspect("aqua", 10)
    .aspect("ordo", 8)
    .vis(50)
    .output(item("essentialcraft:magicalporkchop"))
    .register()

// EC4 Magical Wings (additional recipe before elemental)
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .researchKey("ELEMENTALTOOLS")
    .row("PWW")
    .row("PFF")
    .row("MFF")
    .key("F", item("roots:mystic_feather"))
    .key("M", item("essentialcraft:storage", 3))
    .key("P", ore("plateMagic"))
    .key("W", item("actuallyadditions:item_misc", 15))
    .aspect("aer", 20)
    .aspect("ignis", 10)
    .vis(50)
    .output(item("essentialcraft:magicalwings"))
    .register()
