
// Mining Drill (requiring plates because otherwise there is an useless crafting component)
crafting.remove("immersiveengineering:tool/drillhead_iron")
crafting.remove("immersiveengineering:tool/drillhead_steel")
crafting.shapedBuilder()
        .name("tier3/qol/steel_drill_head")
        .output(item("immersiveengineering:drillhead"))
        .matrix("PP ", "BBP", "PP ")
        .key("P", ore("plateSteel")).key("B", ore("blockSteel"))
        .mirrored()
        .register()
crafting.shapedBuilder()
        .name("tier3/qol/iron_drill_head")
        .output(item("immersiveengineering:drillhead", 1))
        .matrix("PP ", "BBP", "PP ")
        .key("P", ore("plateIron")).key("B", ore("blockIron"))
        .mirrored()
        .register()

// Bullets (avoid useless crafting components)
crafting.remove("immersiveengineering:material/empty_shell")
crafting.shapedBuilder()
        .name("tier3/qol/bullet/shell")
        .output(item("immersiveengineering:bullet", 1) * 5)
        .matrix("PRP", "PRP", " C ")
        .key("P", ore("paper")).key("R", ore("dyeRed")).key("C", ore("plateCopper"))
        .register()

crafting.remove("immersiveengineering:material/empty_casing")
crafting.shapedBuilder()
        .name("tier3/qol/bullet/casing")
        .output(item("immersiveengineering:bullet") * 5)
        .matrix("C C", "C C", " C ")
        .key("C", ore("plateCopper"))
        .register()

// Tool Upgrades (avoid useless crafting components, don't require HV)
crafting.remove("immersiveengineering:toolupgrades/railgun_scope")
crafting.shapedBuilder()
        .name("tier3/qol/upgrade/railgun_scope")
        .output(item("immersiveengineering:toolupgrade", 8))
        .matrix("PC ", "C C", " CP")
        .key("P", ore("paneGlass")).key("C", ore("plateCopper"))
        .register()

crafting.remove("immersiveengineering:toolupgrades/railgun_capacitors")
crafting.shapedBuilder()
        .name("tier3/qol/upgrade/railgun_capacitors")
        .output(item("immersiveengineering:toolupgrade", 9))
        .matrix("CCC", "PPP")
        .key("P", item("immersiveengineering:metal_device0", 1)).key("C", item("immersiveengineering:wirecoil", 1))
        .register()

