// Alchemical Chest
crafting.remove("projecte:alchemical_chest")
crafting.shapedBuilder()
        .name("machines/projecte/alch_chest")
        .output(item("projecte:alchemical_chest"))
        .matrix("DTD", "SLS", "ICI")
        .key("D", item("minecraft:diamond"))
        .key("T", ore("ingotThaumium"))
        .key("S", ore("stone"))
        .key("L", item("essentialcraft:genitem", 45))
        .key("I", item("minecraft:iron_ingot"))
        .key("C", item("ironchest:iron_chest", 1))
        .register()

// Philosopher's Stone
// TODO: move to QMD machines

// Repair Talisman
crafting.remove("projecte:item.pe_repair_talisman")
crafting.shapedBuilder()
        .name("equipment/projecte/repair_talisman")
        .output(item("projecte:item.pe_repair_talisman"))
        .matrix("GBC", "SPS", "CBG")
        .key("B", item("gateway:starsteel_ingot"))
        .key("C", ore("ingotManasteel"))
        .key("G", item("naturesaura:infused_iron"))
        .key("P", item("minecraft:paper"))
        .key("S", item("minecraft:string"))
        .register()

// Matters
crafting.remove("projecte:item.pe_matter_0")
crafting.remove("projecte:item.pe_matter_1")
crafting.remove("projecte:item.pe_matter_1_alt")

// Iron Band
crafting.remove("projecte:item.pe_ring_iron_band")
crafting.remove("projecte:item.pe_ring_iron_band_alt")
crafting.shapedBuilder()
        .name("equipment/projecte/iron_band")
        .output(item("projecte:item.pe_ring_iron_band"))
        .matrix("INI", "NKN", "INI")
        .key("I", item("minecraft:iron_ingot"))
        .key("N", item("minecraft:iron_nugget"))
        .key("K", item("kami:ichorium_ingot"))
        .register()

// Ignition Ring
crafting.remove("projecte:item.pe_ignition_0")
crafting.shapedBuilder()
        .name("equipment/projecte/ignition_ring")
        .output(item("projecte:item.pe_ignition"))
        .matrix("FTF", "MBM", "FTF")
        .key("B", item("projecte:item.pe_ring_iron_band"))
        .key("M", item("projecte:item.pe_matter"))
        .key("F", item("minecraft:flint_and_steel"))
        .key("T", item("embers:ember_cluster"))
        .register()

// Swiftwolf's Rending Gale
crafting.remove("projecte:item.pe_swrg")
crafting.shapedBuilder()
        .name("equipment/projecte/swiftwolf")
        .output(item("projecte:item.pe_swrg"))
        .matrix("RFR", "LBL", "RFR")
        .key("B", item("projecte:item.pe_ring_iron_band"))
        .key("L", item("essentialcraft:charm", 6))
        .key("F", item("roots:mystic_feather"))
        .key("R", item("projecte:item.pe_matter", 1))
        .register()

// Body Stone
crafting.remove("projecte:item.pe_body_stone_0")
crafting.shapedBuilder()
        .name("equipment/projecte/body_stone")
        .output(item("projecte:item.pe_body_stone"))
        .matrix("SSS", "MNM", "SSS")
        .key("S", item("minecraft:sugar"))
        .key("M", item("projecte:item.pe_matter"))
        .key("N", item("calculator:hungermodule"))
        .register()

// Soul Stone
crafting.remove("projecte:item.pe_soul_stone_0")
crafting.shapedBuilder()
        .name("equipment/projecte/soul_stone")
        .output(item("projecte:item.pe_soul_stone"))
        .matrix("SSS", "MNM", "SSS")
        .key("S", item("minecraft:glowstone_dust"))
        .key("M", item("projecte:item.pe_matter"))
        .key("N", item("calculator:healthmodule"))
        .register()

// Mind Stone
crafting.remove("projecte:item.pe_mind_stone_0")
crafting.shapedBuilder()
        .name("equipment/projecte/mind_stone")
        .output(item("projecte:item.pe_mind_stone"))
        .matrix("SSS", "MNM", "SSS")
        .key("S", item("minecraft:book"))
        .key("M", item("projecte:item.pe_matter"))
        .key("N", item("xreliquary:hero_medallion"))
        .register()

// Destruction Catalyst
crafting.remove("projecte:item.pe_destruction_catalyst")
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey("INFUSION")
    .mainInput(item("xreliquary:destruction_catalyst"))
    .output(item("projecte:item.pe_destruction_catalyst"))
    .aspect(aspect("ignis") * 100, aspect("perditio") * 100)
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .instability(24)
    .register()

// Hyperkinetic Lens
crafting.remove("projecte:item.pe_hyperkinetic_lens")
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey("INFUSION")
    .mainInput(item("calculator:grenade"))
    .output(item("projecte:item.pe_hyperkinetic_lens"))
    .aspect(aspect("ignis") * 100, aspect("perditio") * 100)
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .input(item("projecte:item.pe_matter", 1))
    .instability(24)
    .register()

// Evertide Amulet
crafting.remove("projecte:item.pe_evertide_amulet")
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey("INFUSION")
    .mainInput(item("xreliquary:emperor_chalice"))
    .output(item("projecte:item.pe_evertide_amulet"))
    .aspect(aspect("aqua") * 20, aspect("motus") * 20)
    .input(item("essentialcraft:genitem", 6))
    .input(item("essentialcraft:compressed", 1))
    .input(item("essentialcraft:genitem", 6))
    .input(item("essentialcraft:compressed", 1))
    .input(item("essentialcraft:genitem", 6))
    .input(item("essentialcraft:compressed", 1))
    .instability(3)
    .register()
