// Sigil of Consuming (tier 6 -> tier 5)
mods.thaumcraft.infusion_crafting.removeByOutput(item("thaumictinkerer:consuming_sigil"))
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey("TT_CONSUMING_SIGIL")
    .mainInput(item("thaumcraft:baubles", 1))
    .output(item("thaumictinkerer:consuming_sigil"))
    .aspect(aspect("vacuos") * 25)
    .input(item("minecraft:lava_bucket"))
    .input(item("actuallyadditions:item_crystal", 3))
    .input(item("prodigytech:inferno_crystal"))
    .instability(2)
    .register()