// Black Quartz
mods.embers.stamper.recipeBuilder()
    .stamp(item("embers:stamp_flat"))
    .input(item("minecraft:quartz"))
    .fluidInput(fluid("oil") * 100)
    .output(item("actuallyadditions:item_misc", 5))
    .register()

// Empowerers
mods.actuallyadditions.empowerer.recipeBuilder()
    .mainInput(item("actuallyadditions:item_misc", 23))
    .input(item("actuallyadditions:item_canola_seed"), item("calculator:prunaeseeds"), item("actuallyadditions:item_canola_seed"), item("calculator:prunaeseeds"))
    .output(item("actuallyadditions:item_misc", 24))
    .time(40)
    .energy(4000)
    .register()

mods.actuallyadditions.empowerer.recipeBuilder()
    .mainInput(item("actuallyadditions:item_crystal"))
    .input(item("industrialforegoing:artificial_dye", 14), item("thermalfoundation:material", 893), item("calculator:firecoal"), item("extrautils2:ingredients", 11))
    .output(item("actuallyadditions:item_crystal_empowered"))
    .color(0xf90000)
    .time(60)
    .energy(12000)
    .register()

mods.actuallyadditions.empowerer.recipeBuilder()
    .mainInput(item("actuallyadditions:item_crystal", 1))
    .input(item("industrialforegoing:artificial_dye", 11), item("aetherworks:item_geode", 1), item("astralsorcery:itemcraftingcomponent", 1), item("xreliquary:mob_ingredient", 10))
    .output(item("actuallyadditions:item_crystal_empowered", 1))
    .color(0x191a8c)
    .time(60)
    .energy(12000)
    .register()

mods.actuallyadditions.empowerer.recipeBuilder()
    .mainInput(item("actuallyadditions:item_crystal", 2))
    .input(item("industrialforegoing:artificial_dye", 3), item("calculator:smalltanzanite"), item("prodigytech:tartaric_stoker"), item("integrateddynamics:crystalized_menril_chunk"))
    .output(item("actuallyadditions:item_crystal_empowered", 2))
    .color(0x9a9cff)
    .time(60)
    .energy(12000)
    .register()

mods.actuallyadditions.empowerer.recipeBuilder()
    .mainInput(item("actuallyadditions:item_crystal", 3))
    .input(item("industrialforegoing:artificial_dye", 7), item("crimsonrevelations:crimson_plate"), item("astralsorcery:itemusabledust", 1), item("calculator:coaldust"))
    .output(item("actuallyadditions:item_crystal_empowered", 3))
    .color(0x171717)
    .time(60)
    .energy(12000)
    .register()

mods.actuallyadditions.empowerer.recipeBuilder()
    .mainInput(item("actuallyadditions:item_crystal", 4))
    .input(item("industrialforegoing:artificial_dye", 5), item("nuclearcraft:dust", 9), item("calculator:pear"), item("thermalfoundation:material", 819))
    .output(item("actuallyadditions:item_crystal_empowered", 4))
    .color(0x04d601)
    .time(60)
    .energy(12000)
    .register()

mods.actuallyadditions.empowerer.recipeBuilder()
    .mainInput(item("actuallyadditions:item_crystal", 5))
    .input(item("industrialforegoing:artificial_dye"), item("extrautils2:ingredients", 5), item("industrialforegoing:plastic"), item("astralsorcery:itemperkgem", 2))
    .output(item("actuallyadditions:item_crystal_empowered", 5))
    .color(0xf5f0ff)
    .time(60)
    .energy(12000)
    .register()
