// Dust Grinding
mods.botania.mana_infusion.recipeBuilder()
    .input(item("enderio:item_material", 14))
    .output(item("enderio:item_material", 36))
    .mana(6000)
    .catalyst(blockstate("naturesaura:crushing_catalyst"))
    .register()
mods.botania.mana_infusion.recipeBuilder()
    .input(item("enderio:item_material", 15))
    .output(item("enderio:item_material", 35))
    .mana(6000)
    .catalyst(blockstate("naturesaura:crushing_catalyst"))
    .register()
mods.botania.mana_infusion.recipeBuilder()
    .input(item("enderio:item_material", 16))
    .output(item("enderio:item_material", 37))
    .mana(15000)
    .catalyst(blockstate("naturesaura:crushing_catalyst"))
    .register()
mods.botania.mana_infusion.recipeBuilder()
    .input(item("enderio:item_material", 19))
    .output(item("enderio:item_material", 34))
    .mana(15000)
    .catalyst(blockstate("naturesaura:crushing_catalyst"))
    .register()