// Elemental Crystals
crafting.remove("essentialcraft:gem_elemental")
mods.roots.pyre.recipeBuilder()
    .name("tier1/elemental_block")
    .input(item("essentialcraft:compressed"), item("essentialcraft:compressed", 1), item("essentialcraft:compressed", 2),
           item("essentialcraft:compressed", 3), ore("gunpowder"))
    .output(item("essentialcraft:compressed", 4) * 4)
    .burnTime(300)
    .register()

// Foci
crafting.removeByOutput(item("essentialcraft:wfocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune"), item("essentialcraft:genitem"))
    .output(item("essentialcraft:wfocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(0.2f)
    .lowerBalance(0.0f)
    .register()

crafting.removeByOutput(item("essentialcraft:ffocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune", 1), item("essentialcraft:genitem"))
    .output(item("essentialcraft:ffocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(2.0f)
    .lowerBalance(1.8f)
    .register()

crafting.removeByOutput(item("essentialcraft:efocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune", 2), item("essentialcraft:genitem"))
    .output(item("essentialcraft:efocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(1.1f)
    .lowerBalance(0.9f)
    .register()

crafting.removeByOutput(item("essentialcraft:afocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune", 3), item("essentialcraft:genitem"))
    .output(item("essentialcraft:afocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(1.1f)
    .lowerBalance(0.9f)
    .register()

// Magic Fortified Things
mods.essentialcraft.radiating_chamber.removeByOutput(item("essentialcraft:fortifiedstone"))
mods.essentialcraft.radiating_chamber.removeByOutput(item("essentialcraft:fortifiedglass"))

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey("UNLOCKALCHEMY")
    .catalyst(item("thaumcraft:stone_arcane"))
    .output(item("essentialcraft:fortifiedstone") * 4)
    .aspect(aspect("praemunio") * 5)
    .register()

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey("UNLOCKALCHEMY")
    .catalyst(item("thermalfoundation:glass", 3))
    .output(item("essentialcraft:fortifiedglass") * 4)
    .aspect(aspect("praemunio") * 5)
    .register()

// Eye of Absorption
crafting.remove("essentialcraft:eye_of_absorption")
mods.embers.stamper.recipeBuilder()
    .stamp(item("thaumcraft:morphic_resonator"))
    .input(item("mysticalworld:pearl"))
    .output(item("essentialcraft:genitem", 23))
    .fluidInput(fluid("blaze_superfuel") * 200)
    .register()

// MRU Collecting Device
crafting.remove("essentialcraft:mru_catcher")
crafting.shapedBuilder()
    .name("tier5/mru_collecting_device")
    .output(item("essentialcraft:genitem", 29) * 8)
    .matrix("BBB", "CBC", "ECE")
    .key("B", item("thaumcraft:ingot", 2))
    .key("C", item("theaurorian:scrapcrystalline"))
    .key("E", item("essentialcraft:gem_elemental", 4))
    .register()

// MRU Linking Device
crafting.remove("essentialcraft:matrix_link")
crafting.shapedBuilder()
    .name("tier5/mru_linking_device")
    .output(item("essentialcraft:genitem", 28) * 8)
    .matrix("ECE", "DBD", "BBB")
    .key("B", item("thaumcraft:ingot", 2))
    .key("C", item("theaurorian:scrapcrystalline"))
    .key("E", item("essentialcraft:gem_elemental", 4))
    .key("D", item("minecraft:emerald"))
    .register()

// Elemental Core
crafting.remove("essentialcraft:elemental_core")
crafting.shapedBuilder()
    .name("tier5/elemental_core")
    .output(item("essentialcraft:genitem", 1))
    .matrix("IFI", "FEF", "IFI")
    .key("F", item("essentialcraft:fortifiedstone"))
    .key("I", item("theaurorian:ceruleaningot"))
    .key("E", item("essentialcraft:gem_elemental", 4))
    .register()

// Bound Gem
crafting.remove("essentialcraft:bound_gem")
mods.thaumcraft.crucible.recipeBuilder()
    .researchKey("UNLOCKALCHEMY")
    .catalyst(item("essentialcraft:gem_elemental", 4))
    .output(item("essentialcraft:bound_gem"))
    .aspect(aspect("potentia") * 4, aspect("volatus") * 2)
    .register()

// Heat Rod
crafting.remove("essentialcraft:heating_rod")
crafting.shapedBuilder()
    .name("tier5/heating_rod")
    .output(item("essentialcraft:genitem", 25))
    .matrix("FDF", "FBF", "FDF")
    .key("F", item("essentialcraft:gem_elemental"))
    .key("D", item("thermalfoundation:material", 356))
    .key("B", item("thaumcraft:plate"))
    .register()

// Iron Frame
crafting.remove("essentialcraft:iron_support")
crafting.shapedBuilder()
    .name("tier5/ec4_iron_frame")
    .output(item("essentialcraft:genitem", 26) * 4)
    .matrix("IEI", "EIE", "IEI")
    .key("E", item("essentialcraft:gem_elemental", 4))
    .key("I", item("thaumcraft:plate", 2))
    .register()
