// Elemental Crystals
crafting.remove("essentialcraft:gem_elemental")
mods.roots.pyre.recipeBuilder()
    .name("tier1/elemental_block")
    .input(item("essentialcraft:compressed"), item("essentialcraft:compressed", 1), item("essentialcraft:compressed", 2),
           item("essentialcraft:compressed", 3), ore("gunpowder"))
    .output(item("essentialcraft:compressed", 4) * 4)
    .burnTime(300)
    .register()

// Foci
crafting.removeByOutput(item("essentialcraft:wfocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune"), item("essentialcraft:genitem"))
    .output(item("essentialcraft:wfocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(0.2f)
    .lowerBalance(0.0f)
    .register()

crafting.removeByOutput(item("essentialcraft:ffocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune", 1), item("essentialcraft:genitem"))
    .output(item("essentialcraft:ffocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(2.0f)
    .lowerBalance(1.8f)
    .register()

crafting.removeByOutput(item("essentialcraft:efocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune", 2), item("essentialcraft:genitem"))
    .output(item("essentialcraft:efocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(1.1f)
    .lowerBalance(0.9f)
    .register()

crafting.removeByOutput(item("essentialcraft:afocus"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:rune", 3), item("essentialcraft:genitem"))
    .output(item("essentialcraft:afocus"))
    .time(240)
    .mruPerTick(10.0f)
    .upperBalance(1.1f)
    .lowerBalance(0.9f)
    .register()
