import classes.MachineHelper

// Salis Mundus
crafting.removeByOutput(item("thaumcraft:salis_mundus"))
mods.jei.description.remove(item("thaumcraft:salis_mundus"))
mods.roots.fey_crafter.recipeBuilder()
    .name("tier4/salis_mundus")
    .input(item("minecraft:redstone"), item("minecraft:glowstone_dust"), item("gateway:moonlight_powder"), item("actuallyadditions:item_dust", 7), item("roots:runic_dust"))
    .output(item("thaumcraft:salis_mundus") * 4)
    .xp(20)
    .register()

MachineHelper.crushing()
    .input(item("theaurorian:moongem"))
    .output(item("gateway:moonlight_powder") * 2)
    .register()

// Crystal Cluster
mods.thaumcraft.crucible.removeByOutput(item("kamitesque:crystal_cluster"))
mods.thaumcraft.crucible.removeByOutput(item("kamitesque:pure_shard"))
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("thaumicaugmentation:strange_crystal"), item("essentialcraft:genitem", 48))
    .output(item("kamitesque:crystal_cluster"))
    .time(80)
    .mruPerTick(12.0f)
    .register()

// Pure Shard
furnace.removeByInput(item("kamitesque:crystal_cluster"))
furnace.removeByOutput(item("kamitesque:pure_shard"))
mods.thaumcraft.smelting_bonus.removeByOutput(item("kamitesque:pure_shard"))
furnace.add(item("kamitesque:crystal_cluster"), item("ee:star_shard") * 8)
mods.thaumcraft.smelting_bonus.recipeBuilder()
    .input(item("kamitesque:crystal_cluster"))
    .output(item("kamitesque:pure_shard"))
    .chance(1.0F)
    .register()

mods.advancedrocketry.crystallizer.recipeBuilder()
    .input(item("thaumicaugmentation:strange_crystal"), item("ee:star_shard") * 4, item("astralsorcery:itemcraftingcomponent", 4))
    .output(item("thaumicaugmentation:strange_crystal") * 2)
    .power(400)
    .time(160)
    .register()

// Ichor
mods.thaumcraft.infusion_crafting.removeByOutput(item("kami:ichor"))
mods.embers.alchemy.recipeBuilder()
    .input(item("botania:storage", 3), item("thaumcraft:primordial_pearl"), item("essentialcraft:genitem", 23), item("ee:plate"), item("crimsonrevelations:crimson_fabric"))
    .output(item("kami:ichor_block"))
    .setAspect("overworld", 16, 24)
    .setAspect("nether", 16, 24)
    .setAspect("ender", 16, 24)
    .setAspect("emptiness", 16, 24)
    .register()

// cheaper Ichorium
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .researchKey("KAMI_ICHORIUM")
    .mainInput(item("essentialcraft:voidstone"))
    .output(item("kami:ichorium_block"))
    .aspect(aspect("aer") * 25, aspect("terra") * 25, aspect("ignis") * 25, aspect("aqua") * 25, aspect("metallum") * 50)
    .input(item("kami:ichor"))
    .input(item("kami:ichor"))
    .input(item("kami:ichor"))
    .input(item("kami:ichor"))
    .input(item("thaumcraft:phial", 1).withNbt(["Aspects": [["key": "potentia", "amount": 10]]]))
    .input(item("thaumcraft:salis_mundus"))
    .input(item("thaumcraft:salis_mundus"))
    .input(item("thaumcraft:salis_mundus"))
    .input(item("thaumcraft:salis_mundus"))
    .input(item("thaumcraft:phial", 1).withNbt(["Aspects": [["key": "desiderium", "amount": 10]]]))
    .instability(20)
    .register()
