// Diamond (Coal line, tier 6)
mods.calculator.fabrication_chamber.recipeBuilder()
    .input(item("calculator:circuitboard:3").withNbt([Stable: 0, Analysed: 1]), item("calculator:circuitboard:13").withNbt([Stable: 0, Analysed: 1]))
    .output(item("gateway:compression_core"))
    .register()

mods.essentialcraft.magician_table.recipeBuilder()
    .input(item("gateway:compression_core"), item("nuclearcraft:ingot_block", 8), item("thermalfoundation:storage_resource"), item("thermalfoundation:storage_resource"), item("thermalfoundation:storage_resource"))
    .output(item("minecraft:diamond"))
    .mru(600)
    .register()

mods.essentialcraft.magician_table.recipeBuilder()
    .input(item("gateway:compression_core"), item("nuclearcraft:ingot_block", 8), item("minecraft:coal_block"), item("minecraft:coal_block"), item("minecraft:coal_block"))
    .output(item("minecraft:diamond"))
    .mru(600)
    .register()

// Diamond + Lapis (Pale line, tier 7)
mods.thaumcraft.crucible.recipeBuilder()
    .researchKey("UNLOCKALCHEMY@3")
    .catalyst(item("essentialcraft:genitem", 40))
    .output(item("minecraft:diamond"))
    .aspect(aspect("ordo") * 10, aspect("desiderium") * 10)
    .register()

// 46 Lapis + 1 Diamond => 4 Pale Gem => 4 Diamond => 12 Weakened Diamond + 24 Lapis + 1 Diamond => 8 Crystalline Aerogel => 72 Lapis (gaining +50)
mods.theaurorian.moonlight_forge.recipeBuilder()
    .input(item("aether_legacy:aerogel") * 2, item("calculator:weakeneddiamond") * 3)
    .output(item("gateway:crystalline_aerogel") * 2)
    .register()

mods.astralsorcery.light_transmutation.recipeBuilder()
    .input(blockstate("gateway:crystalline_aerogel"))
    .output(blockstate("minecraft:lapis_block"))
    .cost(25.0)
    .register()

// Lapis (Flower line, tier 5)
mods.essentialcraft.radiating_chamber.recipeBuilder()
    .input(item("botania:dye", 11), item("gateway:moonlight_powder"))
    .output(item("actuallyadditions:item_dust", 4) * 8)
    .time(160)
    .mruPerTick(10.0f)
    .register()

// Quartz (Sand line, tier 6)
mods.essentialcraft.magician_table.recipeBuilder()
    .input(item("gateway:compression_core"), item("extrautils2:compressedsand"), item("extrautils2:compressedsand"), item("extrautils2:compressedsand"), item("extrautils2:compressedsand"))
    .output(item("minecraft:quartz") * 4)
    .mru(400)
    .register()
