import classes.MachineHelper

// 0 - smeltery
// 1 - embers
// 2 - thermal/ftech
// 3 - nuclearcraft
def recipes = [
    // Metals
    [item("minecraft:iron_ingot") | item("thermalfoundation:material"), fluid("iron") * 144, 1, 0],
    [item("minecraft:iron_block"), fluid("iron") * 1296, 8, 0],
    [item("minecraft:gold_ingot") | item("thermalfoundation:material", 1), fluid("gold") * 144, 1, 0],
    [item("minecraft:gold_block"), fluid("gold") * 1296, 8, 0],
    [item("thermalfoundation:material", 64) | item("thermalfoundation:material", 128), fluid("copper") * 144, 1, 0],
    [item("thermalfoundation:storage"), fluid("copper") * 1296, 8, 0],
    [item("thermalfoundation:material", 65) | item("thermalfoundation:material", 129), fluid("tin") * 144, 1, 0],
    [item("thermalfoundation:storage", 1), fluid("tin") * 1296, 8, 0],
    [item("thermalfoundation:material", 66) | item("thermalfoundation:material", 130), fluid("silver") * 144, 1, 0],
    [item("thermalfoundation:storage", 2), fluid("silver") * 1296, 8, 0],
    [item("thermalfoundation:material", 67) | item("thermalfoundation:material", 131), fluid("lead") * 144, 1, 0],
    [item("thermalfoundation:storage", 3), fluid("lead") * 1296, 8, 0],
    [item("thermalfoundation:material", 68) | item("thermalfoundation:material", 132), fluid("aluminum") * 144, 1, 0],
    [item("thermalfoundation:storage", 4), fluid("aluminum") * 1296, 8, 0],
    [item("thermalfoundation:material", 69) | item("thermalfoundation:material", 133), fluid("nickel") * 144, 1, 0],
    [item("thermalfoundation:storage", 5), fluid("nickel") * 1296, 8, 0],
    [item("thermalfoundation:material", 70) | item("thermalfoundation:material", 134), fluid("platinum") * 144, 2, 1],
    [item("thermalfoundation:storage", 6), fluid("platinum") * 1296, 16, 1],
    [item("thermalfoundation:material", 71) | item("thermalfoundation:material", 135), fluid("iridium") * 144, 2, 1],
    [item("thermalfoundation:storage", 7), fluid("iridium") * 1296, 16, 1],
    [item("enderio:item_material", 31) | item("tconstruct:ingots"), fluid("cobalt") * 144, 1, 1],
    [item("tconstruct:metal"), fluid("cobalt") * 1296, 8, 1],
    [item("enderio:item_material", 30) | item("tconstruct:ingots", 1), fluid("ardite") * 144, 1, 1],
    [item("tconstruct:metal", 1), fluid("ardite") * 1296, 8, 1],
    [item("qmd:dust") | item("qmd:ingot"), fluid("tungsten") * 144, 1, 2],
    [item("qmd:dust", 1) | item("qmd:ingot", 1), fluid("niobium") * 144, 1, 2],
    [item("qmd:dust", 2) | item("qmd:ingot", 2), fluid("chromium") * 144, 1, 2],
    [item("qmd:dust", 6) | item("qmd:ingot", 6), fluid("hafnium") * 144, 1, 2],
    [item("qmd:dust", 7) | item("qmd:ingot", 7), fluid("zinc") * 144, 1, 0],
    [item("qmd:dust", 8) | item("qmd:ingot", 8), fluid("osmium") * 144, 1, 2],
    [item("qmd:dust", 11) | item("qmd:ingot", 11), fluid("sodium") * 144, 1, 3],
    [item("qmd:dust", 12) | item("qmd:ingot", 12), fluid("potassium") * 144, 1, 3],
    [item("qmd:dust", 13) | item("qmd:ingot", 13), fluid("calcium") * 144, 1, 2],
    [item("qmd:dust", 14) | item("qmd:ingot", 14), fluid("strontium") * 144, 1, 2],
    [item("qmd:dust", 15) | item("qmd:ingot", 15), fluid("barium") * 144, 1, 2],
    [item("qmd:dust2") | item("qmd:ingot2"), fluid("yttrium") * 144, 1, 2],
    [item("qmd:dust2", 1) | item("qmd:ingot2", 1), fluid("neodymium") * 144, 1, 2],
    [item("qmd:ingot2", 2), fluid("mercury") * 144, 0.5, 2],
    [item("qmd:dust2", 2), fluid("iodine") * 144, 0.5, 2],
    [item("qmd:dust2", 3) | item("nuclearcraft:alloy", 18), fluid("samarium") * 144, 1, 2],
    [item("qmd:dust2", 5), fluid("erbium") * 144, 1, 2],
    [item("qmd:dust2", 6), fluid("ytterbium") * 144, 1, 2],
    [item("nuclearcraft:dust", 3) | item("nuclearcraft:ingot", 3), fluid("thorium") * 144, 1, 0],
    [item("nuclearcraft:ingot_block", 3), fluid("thorium") * 1296, 8, 0],
    [item("nuclearcraft:dust", 4) | item("nuclearcraft:ingot", 4), fluid("uranium") * 144, 1, 0],
    [item("nuclearcraft:ingot_block", 4), fluid("uranium") * 1296, 8, 0],
    [item("nuclearcraft:dust", 5) | item("nuclearcraft:ingot", 5), fluid("boron") * 144, 1, 0],
    [item("nuclearcraft:ingot_block", 5), fluid("boron") * 1296, 8, 0],
    [item("nuclearcraft:dust", 6) | item("nuclearcraft:ingot", 6), fluid("lithium") * 144, 1, 0],
    [item("nuclearcraft:ingot_block", 6), fluid("lithium") * 1296, 8, 0],
    [item("nuclearcraft:dust", 7) | item("nuclearcraft:ingot", 7), fluid("magnesium") * 144, 1, 0],
    [item("nuclearcraft:ingot_block", 7), fluid("magnesium") * 1296, 8, 0],
    [item("nuclearcraft:dust", 8) | item("nuclearcraft:ingot", 8), fluid("carbon") * 100, 1, 3],
    [item("nuclearcraft:ingot_block", 8), fluid("carbon") * 900, 8, 3],
    [item("nuclearcraft:dust", 9) | item("nuclearcraft:ingot", 9), fluid("beryllium") * 144, 1, 0],
    [item("nuclearcraft:ingot_block", 9), fluid("beryllium") * 1296, 8, 0],
    [item("nuclearcraft:dust", 10) | item("nuclearcraft:ingot", 10), fluid("zirconium") * 144, 1, 1],
    [item("nuclearcraft:ingot_block", 10), fluid("zirconium") * 1296, 8, 1],
    [item("nuclearcraft:dust", 11) | item("nuclearcraft:ingot", 11), fluid("manganese") * 144, 1, 1],
    [item("nuclearcraft:ingot_block", 11), fluid("manganese") * 1296, 8, 1],
    [item("nuclearcraft:dust", 15) | item("nuclearcraft:ingot", 15), fluid("manganese_dioxide") * 144, 1, 2],
    [item("nuclearcraft:ingot_block", 15), fluid("manganese_dioxide") * 1296, 8, 2],
    [item("nuclearcraft:dust2", 1) | item("nuclearcraft:ingot2", 1), fluid("palladium") * 144, 1, 2],
    [item("nuclearcraft:ingot_block2", 1), fluid("palladium") * 1296, 8, 2],
    [item("nuclearcraft:dust2", 7) | item("nuclearcraft:ingot2", 7), fluid("holmium") * 144, 1, 2],
    [item("nuclearcraft:ingot_block2", 7), fluid("holmium") * 1296, 8, 2],
    [item("nuclearcraft:dust2", 8) | item("nuclearcraft:ingot2", 8), fluid("dysprosium") * 144, 1, 2],
    [item("nuclearcraft:ingot_block2", 8), fluid("dysprosium") * 1296, 8, 2],
    [item("nuclearcraft:dust2", 9) | item("nuclearcraft:ingot2", 9), fluid("gadolinium") * 144, 1, 2],
    [item("nuclearcraft:ingot_block2", 9), fluid("gadolinium") * 1296, 8, 2],
    [item("libvulpes:productingot", 7) | item("libvulpes:productdust", 7), fluid("titanium") * 144, 1, 3],
    [item("libvulpes:metal0", 7), fluid("titanium") * 1296, 8, 3],
    [item("jaopca:dust.cerulean") | item("theaurorian:ceruleaningot"), fluid("cerulean") * 144, 1, 0],
    [item("theaurorian:ceruleanblock"), fluid("cerulean") * 1296, 8, 0],
    [item("jaopca:dust.moonstone") | item("theaurorian:moonstoneingot"), fluid("moonstone") * 144, 1, 0],
    [item("theaurorian:moonstoneblock"), fluid("moonstone") * 1296, 8, 0],
    // Alloys
    [item("thermalfoundation:material", 96) | item("thermalfoundation:material", 160), fluid("steel") * 144, 1, 0],
    [item("thermalfoundation:storage_alloy"), fluid("steel") * 1296, 8, 0],
    [item("thermalfoundation:material", 97) | item("thermalfoundation:material", 161), fluid("electrum") * 144, 1, 0],
    [item("thermalfoundation:storage_alloy", 1), fluid("electrum") * 1296, 8, 0],
    [item("thermalfoundation:material", 98) | item("thermalfoundation:material", 162), fluid("invar") * 144, 1, 0],
    [item("thermalfoundation:storage_alloy", 2), fluid("invar") * 1296, 8, 0],
    [item("thermalfoundation:material", 99) | item("thermalfoundation:material", 163), fluid("bronze") * 144, 1, 0],
    [item("thermalfoundation:storage_alloy", 3), fluid("bronze") * 1296, 8, 0],
    [item("thermalfoundation:material", 100) | item("thermalfoundation:material", 164), fluid("constantan") * 144, 1, 0],
    [item("thermalfoundation:storage_alloy", 4), fluid("constantan") * 1296, 8, 0],
    [item("thermalfoundation:material", 101) | item("thermalfoundation:material", 165), fluid("signalum") * 144, 2, 1],
    [item("thermalfoundation:storage_alloy", 5), fluid("signalum") * 1296, 16, 1],
    [item("thermalfoundation:material", 102) | item("thermalfoundation:material", 166), fluid("lumium") * 144, 2, 1],
    [item("thermalfoundation:storage_alloy", 6), fluid("lumium") * 1296, 16, 1],
    [item("thermalfoundation:material", 103) | item("thermalfoundation:material", 167), fluid("enderium") * 144, 2, 1],
    [item("thermalfoundation:storage_alloy", 7), fluid("enderium") * 1296, 16, 1],
    [item("embers:ingot_dawnstone"), fluid("dawnstone") * 144, 1, 0],
    [item("embers:block_dawnstone"), fluid("dawnstone") * 1296, 8, 0],
    [item("tconstruct:ingots", 2), fluid("manyullyn") * 144, 1, 1],
    [item("tconstruct:metal", 2), fluid("manyullyn") * 1296, 8, 1],
    [item("tconstruct:ingots", 3), fluid("knightslime") * 144, 1, 0],
    [item("tconstruct:metal", 3), fluid("knightslime") * 1296, 8, 0],
    [item("tconstruct:ingots", 4), fluid("pigiron") * 144, 1, 0],
    [item("tconstruct:metal", 4), fluid("pigiron") * 1296, 8, 0],
    [item("tconstruct:ingots", 5), fluid("alubrass") * 144, 1, 0],
    [item("tconstruct:metal", 5), fluid("alubrass") * 1296, 8, 0],
    [item("tconstruct:ingots", 6), fluid("alumite") * 144, 1, 0],
    [item("tconstruct:metal", 6), fluid("alumite") * 1296, 8, 0],
    [item("thaumcraft:ingot", 2), fluid("brass") * 144, 1, 1],
    [item("thaumcraft:metal_brass"), fluid("brass") * 1296, 8, 1],
    [item("enderio:item_alloy_ingot"), fluid("electrical_steel") * 144, 1, 2],
    [item("enderio:block_alloy"), fluid("electrical_steel") * 1296, 8, 2],
    [item("gateway:energetic_alloy_dust") | item("enderio:item_alloy_ingot", 1), fluid("energetic_alloy") * 144, 1, 2],
    [item("enderio:block_alloy", 1), fluid("energetic_alloy") * 1296, 8, 2],
    [item("gateway:vibrant_alloy_dust") | item("enderio:item_alloy_ingot", 2), fluid("vibrant_alloy") * 144, 1, 2],
    [item("enderio:block_alloy", 2), fluid("vibrant_alloy") * 1296, 8, 2],
    [item("gateway:redstone_alloy_dust") | item("enderio:item_alloy_ingot", 3), fluid("redstone_alloy") * 144, 1, 2],
    [item("enderio:block_alloy", 3), fluid("redstone_alloy") * 1296, 8, 2],
    [item("enderio:item_alloy_ingot", 4), fluid("conductive_iron") * 144, 1, 2],
    [item("enderio:block_alloy", 4), fluid("conductive_iron") * 1296, 8, 2],
    [item("gateway:pulsating_iron_dust") | item("enderio:item_alloy_ingot", 5), fluid("pulsating_iron") * 144, 1, 2],
    [item("enderio:block_alloy", 5), fluid("pulsating_iron") * 1296, 8, 2],
    [item("gateway:dark_steel_dust") | item("enderio:item_alloy_ingot", 6), fluid("dark_steel") * 144, 1, 2],
    [item("enderio:block_alloy", 6), fluid("dark_steel") * 1296, 8, 2],
    [item("enderio:item_material", 74) | item("enderio:item_alloy_ingot", 7), fluid("soularium") * 144, 1, 2],
    [item("enderio:block_alloy", 7), fluid("soularium") * 1296, 8, 2],
    [item("enderio:item_alloy_ingot", 8), fluid("end_steel") * 144, 2, 2],
    [item("enderio:block_alloy", 8), fluid("end_steel") * 1296, 16, 2],
    [item("enderio:item_alloy_endergy_ingot", 1), fluid("crystalline_alloy") * 144, 2, 2],
    [item("enderio:block_alloy_endergy", 1), fluid("crystalline_alloy") * 1296, 16, 2],
    [item("enderio:item_alloy_endergy_ingot", 2), fluid("melodic_alloy") * 144, 2, 2],
    [item("enderio:block_alloy_endergy", 2), fluid("melodic_alloy") * 1296, 16, 2],
    [item("enderio:item_alloy_endergy_ingot", 3), fluid("stellar_alloy") * 144, 2, 2],
    [item("enderio:block_alloy_endergy", 3), fluid("stellar_alloy") * 1296, 16, 2],
    [item("nuclearcraft:alloy", 1), fluid("tough") * 144, 1, 0],
    [item("nuclearcraft:alloy", 2), fluid("hard_carbon") * 144, 1, 0],
    [item("nuclearcraft:alloy", 6), fluid("ferroboron") * 144, 1, 0],
    [item("nuclearcraft:alloy", 17), fluid("hastelloy") * 144, 1, 2],
    [item("advancedrocketry:productingot", 7) | item("advancedrocketry:productdust", 7), fluid("titanium_aluminide") * 144, 1, 3],
    [item("advancedrocketry:metal0", 7), fluid("titanium_aluminide") * 1296, 8, 3],
    // Embers
    [item("minecraft:soul_sand"), fluid("oil_soul") * 100, 1, 1],
    [item("soot:ingot_antimony"), fluid("antimony") * 144, 1, 1],
    [item("minecraft:sugar"), fluid("sugar") * 144, 0.5, 1],
    [item("aetherworks:item_resource"), fluid("aetherworks.aetherium_gas") * 16, 0.2, 1],
    // Gem/Dust Ores
    [item("thermalfoundation:material", 768), fluid("coal") * 100, 1, 0],
    [item("minecraft:emerald"), fluid("emerald") * 666, 1, 0],
    [item("minecraft:emerald_block"), fluid("emerald") * 5994, 8, 0],
    [item("minecraft:diamond"), fluid("diamond") * 666, 1, 0],
    [item("minecraft:diamond_block"), fluid("diamond") * 5994, 8, 0],
    [item("minecraft:dye", 4), fluid("lapis") * 666, 1, 0],
    [item("minecraft:lapis_block"), fluid("lapis") * 5994, 8, 0],
    [item("minecraft:quartz") | item("nuclearcraft:gem_dust", 2), fluid("quartz") * 666, 1, 0],
    [item("minecraft:quartz_block"), fluid("quartz") * 2664, 4, 0],
    [item("minecraft:redstone"), fluid("redstone") * 100, 1, 0],
    [item("minecraft:redstone_block"), fluid("redstone") * 900, 8, 0],
    [item("thermalfoundation:material", 893), fluid("redstone") * 500, 1, 2],
    [item("minecraft:glowstone_dust"), fluid("glowstone") * 250, 2, 0],
    [item("minecraft:glowstone"), fluid("glowstone") * 1000, 8, 0],
    [item("thermalfoundation:material", 894), fluid("glowstone") * 1250, 1, 2],
    [item("minecraft:ender_pearl"), fluid("ender") * 250, 2, 2],
    [item("actuallyadditions:block_misc", 6), fluid("ender") * 1000, 6, 2],
    [item("thermalfoundation:material", 895), fluid("ender") * 1250, 1, 2],
    [item("thermalfoundation:material", 771), fluid("sulfur") * 666, 1, 1],
    // Grassoline
    [item("thermalfoundation:material", 817) | item("thermalfoundation:material", 819), fluid("biocrude") * 150, 1, 2],
    [item("thermalfoundation:material", 818) | item("thermalfoundation:material", 826), fluid("biocrude") * 100, 1, 2],
    // NCO Biochem
    [item("nuclearcraft:ground_cocoa_nibs"), fluid("chocolate_liquor") * 144, 0.5, 3],
    [item("nuclearcraft:cocoa_butter"), fluid("cocoa_butter") * 144, 0.2, 3],
    [item("nuclearcraft:unsweetened_chocolate"), fluid("unsweetened_chocolate") * 144, 0.5, 3],
    [item("nuclearcraft:dark_chocolate"), fluid("dark_chocolate") * 144, 0.5, 3],
    [item("nuclearcraft:milk_chocolate"), fluid("milk_chocolate") * 144, 0.5, 3],
    [item("nuclearcraft:gelatin"), fluid("gelatin") * 144, 1, 3],
    [item("nuclearcraft:marshmallow"), fluid("marshmallow") * 144, 1, 3],
    // Special metals
    [item("extrautils2:ingredients", 12), fluid("xu_enchanted_metal") * 144, 1, 0],
    [item("extrautils2:simpledecorative"), fluid("xu_enchanted_metal") * 1296, 8, 0],
    [item("extrautils2:ingredients", 11), fluid("xu_demonic_metal") * 144, 1, 0],
    [item("extrautils2:simpledecorative", 1), fluid("xu_demonic_metal") * 1296, 8, 0],
    [item("extrautils2:ingredients", 17), fluid("xu_evil_metal") * 144, 1, 0],
    [item("extrautils2:simpledecorative", 2), fluid("xu_evil_metal") * 1296, 8, 0],
    [item("kami:ichorium_ingot"), fluid("ichorium") * 144, 2, 2],
    [item("kami:ichorium_block"), fluid("ichorium") * 1296, 16, 2],
    // TConstruct
    [item("minecraft:slime_ball"), fluid("slime") * 250, 0.25, 0],
    [item("tconstruct:slime_congealed"), fluid("slime") * 1000, 1, 0],
    [item("minecraft:slime"), fluid("slime") * 2250, 2.25, 0],
    [item("tconstruct:edible", 1), fluid("blueslime") * 250, 0.25, 0],
    [item("tconstruct:slime_congealed", 1), fluid("blueslime") * 1000, 1, 0],
    [item("tconstruct:slime", 1), fluid("blueslime") * 2250, 2.25, 0],
    [item("tconstruct:edible", 2), fluid("purpleslime") * 250, 0.25, 0],
    [item("tconstruct:slime_congealed", 2), fluid("purpleslime") * 1000, 1, 0],
    [item("tconstruct:slime", 2), fluid("purpleslime") * 2250, 2.25, 0],
    [item("tconstruct:edible", 3), fluid("blood") * 250, 0.25, 0],
    [item("tconstruct:slime_congealed", 3), fluid("blood") * 1000, 1, 0],
    [item("tconstruct:slime", 3), fluid("blood") * 2250, 2.25, 0],
    [item("tconstruct:materials"), fluid("stone") * 144, 0.8, 0],
    [item("minecraft:cobblestone"), fluid("stone") * 36, 0.8, 1],
    [item("extrautils2:compressedcobblestone"), fluid("stone") * 324, 0.8, 2],
    [item("minecraft:obsidian"), fluid("obsidian") * 288, 1.25, 0],
    [ore("dirt"), fluid("dirt") * 144, 0.25, 0],
    [item("minecraft:clay_ball"), fluid("clay") * 144, 0.5, 0],
    [item("minecraft:clay"), fluid("clay") * 576, 2, 0],
    [ore("sand"), fluid("glass") * 1000, 1, 0],
    [ore("blockGlass"), fluid("glass") * 1000, 1, 0],
    // Misc
    [item("integrateddynamics:crystalized_menril_chunk"), fluid("menrilresin") * 250, 0.5, 2],
    [item("integrateddynamics:crystalized_chorus_chunk"), fluid("liquidchorus") * 250, 0.5, 2],
    [item("integrateddynamics:crystalized_menril_block"), fluid("menrilresin") * 2250, 4, 2],
    [item("integrateddynamics:crystalized_chorus_block"), fluid("liquidchorus") * 2250, 4, 2],
    [item("thermalfoundation:material", 1024), fluid("pyrotheum") * 250, 1, 1],
    [item("thermalfoundation:material", 1025), fluid("cryotheum") * 250, 1, 1],
    [item("thermalfoundation:material", 1026), fluid("aerotheum") * 250, 1, 1],
    [item("thermalfoundation:material", 1027), fluid("petrotheum") * 250, 1, 1],
    [item("thermalfoundation:material", 1028), fluid("mana") * 250, 1, 1],
    [item("actuallyadditions:item_solidified_experience"), fluid("experience") * 160, 0.25, 1],
    [item("woot:xpshard"), fluid("experience") * 320, 0.5, 1],
    [item("minecraft:prismarine_shard") | item("minecraft:prismarine_crystals"), fluid("prismarine") * 144, 1, 3],
    [item("minecraft:netherbrick"), fluid("nether_brick") * 72, 0.5, 3],
    [item("minecraft:nether_brick"), fluid("nether_brick") * 288, 2, 3],
    [item("minecraft:purpur_block"), fluid("purpur") * 72, 0.5, 3],
    [item("minecraft:chorus_fruit_popped"), fluid("purpur") * 288, 2, 3],
    [ore("endstone"), fluid("end_stone") * 288, 2, 3],
    // NCO chem
    [item("nuclearcraft:compound", 5), fluid("naoh") * 666, 1, 3],
    [item("nuclearcraft:compound", 6), fluid("koh") * 666, 1, 3],
    [item("nuclearcraft:compound", 11), fluid("alugentum") * 144, 1, 3],
    [item("nuclearcraft:compound", 18), fluid("barium_sulfide") * 144, 1, 3],
    [item("nuclearcraft:gem_dust", 10), fluid("arsenic") * 666, 1, 3],
    [item("qmd:chemical_dust", 3), fluid("sodium_chloride") * 666, 1, 3],
    [item("nuclearcraft:gem", 6), fluid("silicon") * 144, 1, 3],
    [item("nuclearcraft:alloy", 13), fluid("sic_vapor") * 144, 1, 3],
    [item("nuclearcraft:part", 22), fluid("polymethylsilylene_methylene") * 144, 1, 3],
    [item("nuclearcraft:dust2", 3) | item("nuclearcraft:ingot2", 3), fluid("nickel_oxide") * 144, 1, 3],
    [item("nuclearcraft:ingot_block2", 3), fluid("nickel_oxide") * 1296, 8, 3],
    // NCO fission
    [item("nuclearcraft:fission_dust"), fluid("bismuth") * 144, 1, 2],
    [item("nuclearcraft:fission_dust", 1), fluid("radium") * 144, 1, 3],
    [item("nuclearcraft:fission_dust", 2), fluid("polonium") * 144, 1, 3],
    [item("nuclearcraft:fission_dust", 5), fluid("strontium_90") * 144, 1, 3],
    [item("qmd:strontium_90_block"), fluid("strontium_90") * 1296, 8, 3],
    [item("nuclearcraft:fission_dust", 6), fluid("molybdenum") * 144, 1, 2],
    [item("nuclearcraft:material_block"), fluid("molybdenum") * 1296, 8, 2],
    [item("nuclearcraft:fission_dust", 7), fluid("ruthenium_106") * 144, 1, 3],
    [item("nuclearcraft:fission_dust", 8), fluid("caesium_137") * 144, 1, 3],
    [item("nuclearcraft:fission_dust", 9), fluid("promethium_147") * 144, 1, 3],
    [item("nuclearcraft:fission_dust", 10), fluid("europium_155") * 144, 1, 3],
    [item("nuclearcraft:pellet_thorium"), fluid("tbu"), 1, 3],
]

def ncIsotopes = [
    ["uranium", "uranium", [[0, 233], [5, 235], [10, 238]]],
    ["neptunium", "neptunium", [[0, 236], [5, 237]]],
    ["plutonium", "plutonium", [[0, 238], [5, 239], [10, 241], [15, 242]]],
    ["americium", "americium", [[0, 241], [5, 242], [10, 243]]],
    ["curium", "curium", [[0, 243], [5, 245], [10, 246], [15, 247]]],
    ["berkelium", "berkelium", [[0, 247], [5, 248]]],
    ["californium", "californium", [[0, 249], [5, 250], [10, 251], [15, 252]]],
    ["lithium", "lithium", [[0, 6], [1, 7]]],
    ["boron", "boron", [[0, 10], [1, 11]]],
    ["pellet_uranium", "leu", [[0, 233], [4, 235]]],
    ["pellet_uranium", "heu", [[2, 233], [6, 235]]],
    ["pellet_neptunium", "len", [[0, 236]]],
    ["pellet_neptunium", "hen", [[2, 236]]],
    ["pellet_plutonium", "lep", [[0, 239], [4, 241]]],
    ["pellet_plutonium", "hep", [[2, 239], [6, 241]]],
    ["pellet_mixed", "mix", [[0, 239], [2, 241]]],
    ["pellet_americium", "lea", [[0, 242]]],
    ["pellet_americium", "hea", [[2, 242]]],
    ["pellet_curium", "lecm", [[0, 243], [4, 245], [8, 247]]],
    ["pellet_curium", "lecm", [[2, 243], [6, 245], [10, 247]]],
    ["pellet_berkelium", "leb", [[0, 248]]],
    ["pellet_berkelium", "heb", [[2, 248]]],
    ["pellet_californium", "lecf", [[0, 249], [4, 251]]],
    ["pellet_californium", "hecf", [[2, 249], [6, 251]]],
]
for (def it in ncIsotopes) {
    for (def k in it[2]) {
        recipes.add([item("nuclearcraft:${it[0]}", k[0]), fluid("${it[1]}_${k[1]}") * 144, 1, 3])
    }
}

// Soot
def naturalRecipes = [
    [item("minecraft:wheat"), fluid("boiling_wort") * 100],
    [item("minecraft:potato"), fluid("boiling_potato_juice") * 100],
    [item("minecraft:beetroot"), fluid("boiling_beetroot_soup") * 100],
    [item("minecraft:wheat"), fluid("boiling_wort") * 100],
    [item("minecraft:tallgrass", 2), fluid("boiling_wormwood") * 100],
    [item("minecraft:double_plant", 3), fluid("boiling_wormwood") * 200],
]


for (def it in recipes) {
    MachineHelper.melting()
        .minTier(it[3])
        .timeMultiplier(it[2])
        .input(it[0])
        .fluidOutput(it[1]).register()
}

for (def it in naturalRecipes) {
    MachineHelper.melting()
        .minTier(1).maxTier(1)
        .input(it[0])
        .fluidOutput(it[1]).register()
}
