mods.tconstruct.casting_table.removeByOutput(item("minecraft:slime_ball"))
mods.tconstruct.casting_table.recipeBuilder()
    .fluidInput(fluid("slime") * 250)
    .output(item("minecraft:slime_ball"))
    .coolingTime(50)
    .register()

mods.tconstruct.casting_basin.removeByOutput(item("tconstruct:slime_congealed"))
mods.tconstruct.casting_basin.recipeBuilder()
    .fluidInput(fluid("slime") * 1000)
    .output(item("tconstruct:slime_congealed"))
    .coolingTime(100)
    .register()

mods.tconstruct.casting_basin.removeByOutput(item("tconstruct:slime_dirt"))
mods.tconstruct.casting_basin.recipeBuilder()
    .cast(ore("dirt")).consumesCast(true)
    .fluidInput(fluid("slime") * 250)
    .output(item("tconstruct:slime_dirt"))
    .coolingTime(100)
    .register()

mods.tconstruct.entity_melting.removeByOutput(fluid("greenslime"))
mods.tconstruct.entity_melting.recipeBuilder()
    .input(resource("minecraft:slime"))
    .fluidOutput(fluid("slime") * 25)
    .register()
