def anyDrawer = item("functionalstoragelegacy:oak_1")
for (def mat in ["oak", "spruce", "jungle", "birch", "acacia", "dark_oak"]) {
    for (def i in [1, 2, 4]) {
        anyDrawer = anyDrawer | item("functionalstoragelegacy:${mat}_${i}")
    }
}

// Storage Controller
crafting.remove("functionalstoragelegacy:storage_controller")
crafting.shapedBuilder()
        .name("tier4/drawer/controller")
        .output(item("functionalstoragelegacy:storage_controller"))
        .matrix("SES", "DRD", "SES")
        .key("S", item("minecraft:stone")).key("R", item("actuallyadditions:item_crystal", 2)).key("D", anyDrawer)
        .key("E", item("actuallyadditions:block_testifi_bucks_white_wall"))
        .register()

// ~~Controller Slave~~ Controller Extension
crafting.remove("functionalstoragelegacy:controller_extension")
crafting.shapedBuilder()
        .name("tier4/drawer/controller_extension")
        .output(item("functionalstoragelegacy:controller_extension"))
        .matrix("SES", "DRD", "SES")
        .key("S", item("minecraft:stone")).key("R", item("actuallyadditions:item_crystal")).key("D", anyDrawer)
        .key("E", item("actuallyadditions:block_testifi_bucks_white_wall"))
        .register()

// Compacting Drawer (fix recipe to only accept wood drawers)
crafting.remove("functionalstoragelegacy:compacting_drawer")
crafting.shapedBuilder()
        .name("tier2/drawer/compacting_drawer")
        .output(item("functionalstoragelegacy:compacting_drawer"))
        .matrix("SSS", "PDP", "SIS")
        .key("S", item("minecraft:stone")).key("I", item("minecraft:iron_ingot")).key("D", anyDrawer).key("P", item("minecraft:piston"))
        .register()

// Simple Compacting Drawer (fix recipe to only accept wood drawers)
crafting.remove("functionalstoragelegacy:simple_compacting_drawer")
crafting.shapedBuilder()
        .mirrored()
        .name("tier2/drawer/simple_compacting_drawer")
        .output(item("functionalstoragelegacy:simple_compacting_drawer"))
        .matrix("SSS", "SDP", "SIS")
        .key("S", item("minecraft:stone")).key("I", item("minecraft:iron_ingot")).key("D", anyDrawer).key("P", item("minecraft:piston"))
        .register()

// Ender Drawer
crafting.remove("functionalstoragelegacy:ender_drawer")
crafting.shapedBuilder()
        .name("tier7/drawer/ender_drawer")
        .output(item("functionalstoragelegacy:ender_drawer"))
        .matrix("SSS", "DED", "SSS")
        .key("S", ore("plankWood")).key("E", item("enderstorage:ender_storage")).key("D", anyDrawer)
        .register()

// Armory Cabinet
crafting.remove("functionalstoragelegacy:armory_cabinet")
crafting.shapedBuilder()
        .name("tier7/drawer/armory_cabinet")
        .output(item("functionalstoragelegacy:armory_cabinet"))
        .matrix("SDS", "DED", "SNS")
        .key("S", item("minecraft:stone")).key("E", item("enderutilities:storage_0", 3)).key("D", anyDrawer).key("N", item("netherized:netherite_ingot"))
        .register()

// Upgrades (fix compacting drawers being usable + recipe enhancements)
crafting.remove("functionalstoragelegacy:iron_downgrade")
crafting.remove("functionalstoragelegacy:copper_upgrade")
crafting.remove("functionalstoragelegacy:gold_upgrade")
crafting.remove("functionalstoragelegacy:diamond_upgrade")
crafting.remove("functionalstoragelegacy:netherite_upgrade")
crafting.remove("functionalstoragelegacy:void_upgrade")
crafting.remove("functionalstoragelegacy:redstone_upgrade")
crafting.remove("functionalstoragelegacy:pushing_upgrade")
crafting.remove("functionalstoragelegacy:pulling_upgrade")
crafting.remove("functionalstoragelegacy:collector_upgrade")

crafting.shapedBuilder()
        .name("drawer_upgrades/iron")
        .output(item("functionalstoragelegacy:iron_downgrade") * 2)
        .matrix("ISI", "SDS", "ISI")
        .key("S", ore("stickWood")).key("D", anyDrawer).key("I", item("minecraft:iron_ingot"))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/copper")
        .output(item("functionalstoragelegacy:copper_upgrade") * 2)
        .matrix("ISI", "DCD", "ISI")
        .key("S", ore("ingotCopper")).key("D", anyDrawer).key("I", ore("blockCopper")).key("C", item("ironchest:iron_chest"))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/gold")
        .output(item("functionalstoragelegacy:gold_upgrade") * 2)
        .matrix("ISI", "DCD", "ISI")
        .key("S", ore("ingotGold")).key("D", item("functionalstoragelegacy:copper_upgrade")).key("I", ore("blockGold")).key("C", item("ironchest:iron_chest", 1))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/diamond")
        .output(item("functionalstoragelegacy:diamond_upgrade") * 2)
        .matrix("ISI", "DCD", "ISI")
        .key("S", ore("gemDiamond")).key("D", item("functionalstoragelegacy:gold_upgrade")).key("I", ore("blockDiamond")).key("C", item("ironchest:iron_chest", 2))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/netherite")
        .output(item("functionalstoragelegacy:netherite_upgrade") * 2)
        .matrix("ISI", "DCD", "ISI")
        .key("S", item("essentialcraft:genitem", 79)).key("D", item("functionalstoragelegacy:gold_upgrade")).key("I", ore("ingotNetherite"))
        .key("C", item("ironchest:iron_chest", 6))
        .register()

crafting.shapedBuilder()
        .name("drawer_upgrades/void")
        .output(item("functionalstoragelegacy:void_upgrade") * 2)
        .matrix("ISI", "SDS", "ISI")
        .key("S", ore("stickWood")).key("D", anyDrawer).key("I", item("actuallyadditions:item_crystal", 3))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/redstone")
        .output(item("functionalstoragelegacy:redstone_upgrade") * 2)
        .matrix("ISI", "CDC", "ISI")
        .key("S", item("minecraft:redstone_block")).key("D", anyDrawer).key("I", item("minecraft:redstone")).key("C", item("minecraft:comparator"))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/pulling")
        .output(item("functionalstoragelegacy:pulling_upgrade") * 2)
        .matrix("SHS", "SHS", "SDS")
        .key("S", item("minecraft:stone")).key("D", anyDrawer).key("H", item("minecraft:hopper"))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/pushing")
        .output(item("functionalstoragelegacy:pushing_upgrade") * 2)
        .matrix("SDS", "SHS", "SHS")
        .key("S", item("minecraft:stone")).key("D", anyDrawer).key("H", item("minecraft:hopper"))
        .register()
crafting.shapedBuilder()
        .name("drawer_upgrades/collector")
        .output(item("functionalstoragelegacy:collector_upgrade") * 2)
        .matrix("SCS", "RDR", "SCS")
        .key("S", ore("ingotSteel")).key("D", anyDrawer).key("C", item("actuallyadditions:block_ranged_collector")).key("R", item("minecraft:redstone"))
        .register()

// Tools
crafting.remove("functionalstoragelegacy:linking_tool")
crafting.remove("functionalstoragelegacy:configuration_tool")

crafting.shapedBuilder()
        .mirrored()
        .name("tier1/drawers/config_tool")
        .output(item("functionalstoragelegacy:configuration_tool"))
        .matrix("LLL", "LDP", "LGP")
        .key("L", ore("ingotAluminum")).key("P", item("minecraft:paper")).key("D", anyDrawer).key("G", ore("dyeGreen"))
        .register()
crafting.shapedBuilder()
        .mirrored()
        .name("tier1/drawers/linking_tool")
        .output(item("functionalstoragelegacy:linking_tool"))
        .matrix("LLL", "LDP", "LGP")
        .key("L", ore("ingotAluminum")).key("P", item("minecraft:paper")).key("D", anyDrawer).key("G", ore("gemDiamond"))
        .register()

// Fluid Drawers
crafting.remove("functionalstoragelegacy:fluid_1")
crafting.remove("functionalstoragelegacy:fluid_2")
crafting.remove("functionalstoragelegacy:fluid_4")

crafting.shapedBuilder()
        .name("tier3/fluid_drawers/1x")
        .mirrored()
        .output(item("functionalstoragelegacy:fluid_1"))
        .matrix("SSS", "STG", "SSS")
        .key("S", ore("blockSheetmetalIron")).key("T", item("enderio:block_tank")).key("G", ore("blockGlassColorless"))
        .register()
crafting.shapelessBuilder()
        .name("tier3/fluid_drawers/2x")
        .output(item("functionalstoragelegacy:fluid_2") * 2)
        .input(item("functionalstoragelegacy:fluid_1"), item("functionalstoragelegacy:fluid_1"))
        .register()
crafting.shapelessBuilder()
        .name("tier3/fluid_drawers/4x")
        .output(item("functionalstoragelegacy:fluid_4") * 2)
        .input(item("functionalstoragelegacy:fluid_2"), item("functionalstoragelegacy:fluid_2"))
        .register()