// Coke Oven
crafting.remove("immersiveengineering:stone_decoration/cokebrick")
crafting.shapedBuilder()
        .name("tier1/coke_brick")
        .output(item("immersiveengineering:stone_decoration") * 3)
        .matrix("BCB", "CSC", "BCB")
        .key("B", item("minecraft:netherbrick")).key("C", item("minecraft:clay_ball")).key("S", ore("sandstone"))
        .register()

// Kiln
crafting.remove("immersiveengineering:stone_decoration/alloybrick")
crafting.shapedBuilder()
        .name("tier1/kiln_brick")
        .output(item("immersiveengineering:stone_decoration", 10) * 2)
        .matrix("BS", "SB")
        .key("B", item("minecraft:netherbrick")).key("S", ore("sandstone"))
        .register()

// Connectors
crafting.remove("immersiveengineering:connectors/breaker_switch")
crafting.shapedBuilder()
        .name("tier3/connectors/breaker")
        .output(item("immersiveengineering:connector", 9))
        .matrix(" L ", "TCT")
        .key("T", item("minecraft:hardened_clay")).key("L", item("minecraft:lever")).key("C", ore("plateCopper"))
        .register()

crafting.remove("immersiveengineering:connectors/connector_lv")
crafting.shapedBuilder()
        .name("tier3/connectors/lv")
        .output(item("immersiveengineering:connector") * 2)
        .matrix(" C ", "TCT", "TCT")
        .key("T", item("minecraft:hardened_clay")).key("C", ore("plateCopper"))
        .register()

crafting.remove("immersiveengineering:connectors/connector_mv")
crafting.shapedBuilder()
        .name("tier3/connectors/mv")
        .output(item("immersiveengineering:connector", 2) * 2)
        .matrix(" C ", "TCT", "TCT")
        .key("T", item("minecraft:hardened_clay")).key("C", ore("plateSteel"))
        .register()

crafting.remove("immersiveengineering:connectors/connector_hv")
crafting.shapedBuilder()
        .name("tier6/connectors/hv")
        .output(item("immersiveengineering:connector", 4) * 2)
        .matrix(" C ", "TCT", "TCT")
        .key("T", item("minecraft:hardened_clay")).key("C", item("gateway:starsteel_ingot"))
        .register()

crafting.remove("immersiveengineering:connectors/relay_lv")
crafting.shapedBuilder()
        .name("tier3/relays/lv")
        .output(item("immersiveengineering:connector", 1) * 4)
        .matrix(" C ", "TCT")
        .key("T", item("minecraft:hardened_clay")).key("C", ore("plateCopper"))
        .register()

crafting.remove("immersiveengineering:connectors/relay_mv")
crafting.shapedBuilder()
        .name("tier3/relays/mv")
        .output(item("immersiveengineering:connector", 3) * 4)
        .matrix(" C ", "TCT")
        .key("T", item("minecraft:hardened_clay")).key("C", ore("plateSteel"))
        .register()

crafting.remove("immersiveengineering:connectors/relay_hv")
crafting.shapedBuilder()
        .name("tier3/relays/hv")
        .output(item("immersiveengineering:connector", 5) * 4)
        .matrix(" C ", "TCT")
        .key("T", item("minecraft:hardened_clay")).key("C", item("gateway:starsteel_ingot"))
        .register()

// Engineer's Worktable
crafting.remove("immersiveengineering:wooden_devices/workbench")
crafting.shapedBuilder()
        .name("tier3/worktable")
        .output(item("immersiveengineering:wooden_device0", 2))
        .matrix("TTT", "SSS", "C F")
        .key("T", ore("plankTreatedWood")).key("S", ore("ingotSteel")).key("C", item("minecraft:crafting_table"))
        .key("F", item("immersiveengineering:wooden_decoration"))
        .mirrored()
        .register()

// Blast Bricks
crafting.remove("immersiveengineering:stone_decoration/blastbrick")
crafting.shapedBuilder()
        .name("tier3/blast_brick")
        .output(item("immersiveengineering:stone_decoration", 1) * 3)
        .matrix("SBS", "BHB", "SBS")
        .key("S", item("minecraft:netherbrick")).key("B", item("tconstruct:materials")).key("H", item("minecraft:blaze_powder"))
        .register()

// Arc Furnace Bricks
crafting.remove("immersiveengineering:stone_decoration/blastbrick_reinforced")
crafting.shapedBuilder()
        .name("tier4/blast_brick")
        .output(item("immersiveengineering:stone_decoration", 2) * 4)
        .matrix("SBS", "BHB", "SBS")
        .key("S", ore("plateSteel")).key("B", item("immersiveengineering:stone_decoration", 1)).key("H", item("nuclearcraft:ingot", 8))
        .register()

// HV things
crafting.remove("immersiveengineering:metal_decoration/generator")
crafting.shapedBuilder()
        .name("tier6/generator_block")
        .output(item("immersiveengineering:metal_decoration0", 6) * 2)
        .matrix("SSS", "EGE", "SSS")
        .key("E", ore("blockElectrum")).key("S", ore("ingotStarsteel")).key("G", item("immersiveengineering:metal_device1", 3))
        .register()

crafting.remove("immersiveengineering:metal_decoration/radiator")
crafting.shapedBuilder()
        .name("tier6/radiator_block")
        .output(item("immersiveengineering:metal_decoration0", 7) * 2)
        .matrix("ScS", "CGC", "ScS")
        .key("C", ore("blockCopper")).key("c", ore("ingotCopper")).key("S", ore("ingotStarsteel")).key("G", fluid("water") * 1000)
        .register()

crafting.remove("immersiveengineering:metal_devices/coresample_drill")
crafting.shapedBuilder()
        .name("tier6/core_sample_drill")
        .output(item("immersiveengineering:metal_device1", 7))
        .matrix("SFS", "SFS", "ECE")
        .key("S", ore("ingotStarsteel")).key("F", item("immersiveengineering:metal_decoration1"))
        .key("E", item("immersiveengineering:metal_decoration0", 4)).key("C", item("calculator:circuitboard", 1))
        .register()

crafting.remove("immersiveengineering:wirecoils/wirecoil_hv")
crafting.remove("immersiveengineering:wirecoils/wirecoil_hv2")
crafting.shapedBuilder()
        .name("tier6/hv_coil")
        .output(item("immersiveengineering:wirecoil", 2) * 4)
        .matrix(" W ", "SRS", " W ")
        .key("W", item("immersiveengineering:material", 22)).key("S", ore("ingotStarsteel")).key("R", item("immersiveengineering:material", 2))
        .register()

// Garden Cloche
crafting.remove("immersiveengineering:metal_devices/garden_cloche")
crafting.shapedBuilder()
        .name("tier6/garden_cloche")
        .output(item("immersiveengineering:metal_device1", 13))
        .matrix("GTG", "G G", "PLP")
        .key("G", item("calculator:flawlessglass")).key("T", item("calculator:circuitboard", 8)).key("P", ore("plankTreatedWood")).key("L", item("immersiveengineering:material", 8))
        .register()
