// Explosion Furnace
crafting.remove("prodigytech:machine/explosion_furnace")
crafting.shapedBuilder()
        .name("tier2/explosion_furnace")
        .output(item("prodigytech:explosion_furnace"))
        .matrix("BBB", "BAB", "BBB")
        .key("B", ore("bricksStone")).key("A", item("naturesaura:token_anger"))
        .register()

// Incinerator
crafting.remove("prodigytech:machine/incinerator")
crafting.shapedBuilder()
        .name("tier2/incinerator")
        .output(item("prodigytech:incinerator"))
        .matrix("FUF", "FUF", "FSF")
        .key("F", ore("ingotFerramic")).key("U", item("theaurorian:scrapumbra")).key("S", item("naturesaura:token_sorrow"))
        .register()

// Machine Frame
crafting.shapedBuilder()
        .name("tier3/ferramic_machine_frame")
        .output(item("gateway:ferramic_machine_frame"))
        .matrix("FCF", "SGS", "FCF")
        .key("F", item("prodigytech:ferramic_ingot"))
        .key("C", item("prodigytech:carbon_plate"))
        .key("S", item("immersiveengineering:material", 2))
        .key("G", item("immersiveengineering:metal_decoration0", 4))
        .register()

// Solid Fuel Aeroheater
crafting.remove("prodigytech:machine/solid_fuel_aeroheater")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/solid_fuel_aeroheater")
        .output(item("prodigytech:solid_fuel_aeroheater"))
        .matrix("FCF", "RGR")
        .key("C", item("gateway:ferramic_machine_frame")).key("F", item("minecraft:furnace"))
        .key("R", item("roots:runestone")).key("G", item("prodigytech:ferramic_gear"))
        .register()

// Energion Aeroheater
crafting.remove("prodigytech:machine/energion_aeroheater")
crafting.shapedBuilder()
        .name("tier5/energion_aeroheater")
        .output(item("prodigytech:energion_aeroheater"))
        .matrix(" E ", "FCF", "RGR")
        .key("C", item("gateway:ferramic_machine_frame")).key("F", item("minecraft:furnace"))
        .key("G", item("prodigytech:circuit_refined")).key("R", ore("gearDiamond")).key("E", item("prodigytech:energion_dust"))
        .register()

// Tartaric Aeroheater
crafting.remove("prodigytech:machine/tartaric_aeroheater")
crafting.shapedBuilder()
        .name("tier7/tartaric_aeroheater")
        .output(item("prodigytech:tartaric_aeroheater"))
        .matrix(" E ", "FCF", "RGR")
        .key("C", item("gateway:ferramic_machine_frame")).key("F", item("minecraft:furnace"))
        .key("G", item("prodigytech:circuit_perfected")).key("R", ore("ingotZorrasteel")).key("E", item("prodigytech:aeternus_crystal"))
        .register()

// Capacitor Aeroheater
crafting.remove("prodigytech:machine/capacitor_aeroheater")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/capacitor_aeroheater")
        .output(item("prodigytech:capacitor_aeroheater"))
        .matrix(" Ec", "FCF")
        .key("C", item("gateway:ferramic_machine_frame")).key("F", item("minecraft:redstone"))
        .key("c", item("prodigytech:circuit_crude")).key("E", ore("gearLead"))
        .register()

// Rotary Grinder
crafting.remove("prodigytech:machine/rotary_grinder")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/rotary_grinder")
        .output(item("prodigytech:rotary_grinder"))
        .matrix(" Ac", "RCR")
        .key("C", item("gateway:ferramic_machine_frame")).key("R", ore("gearSteel")).key("A", item("theaurorian:crystal")).key("c", item("prodigytech:circuit_crude"))
        .register()

// Heat Sawmill
crafting.remove("prodigytech:machine/heat_sawmill")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/heat_sawmill")
        .output(item("prodigytech:heat_sawmill"))
        .matrix(" Ac", "RCR")
        .key("C", item("gateway:ferramic_machine_frame")).key("R", ore("ingotSteel")).key("A", ore("gearNickel")).key("c", item("prodigytech:circuit_crude"))
        .register()

// Food Purifier
crafting.remove("prodigytech:machine/food_purifier")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/food_purifier")
        .output(item("prodigytech:food_purifier"))
        .matrix(" Ac", "RCR")
        .key("C", item("gateway:ferramic_machine_frame")).key("R", ore("ingotAluminum")).key("A", item("prodigytech:carbon_plate")).key("c", item("prodigytech:circuit_crude"))
        .register()

// Solderer
crafting.remove("prodigytech:machine/solderer")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/solderer")
        .output(item("prodigytech:solderer"))
        .matrix(" G ", "g g", "LCc")
        .key("C", item("gateway:ferramic_machine_frame")).key("G", ore("blockGlowstone")).key("c", item("prodigytech:carbon_plate"))
        .key("L", ore("gearGold")).key("g", ore("blockGlassColorless"))
        .register()

// Ore Refinery
crafting.remove("prodigytech:machine/ore_refinery")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/ore_refinery")
        .output(item("prodigytech:ore_refinery"))
        .matrix(" Ac", "RCR")
        .key("C", item("gateway:ferramic_machine_frame")).key("R", ore("ingotGold")).key("A", item("theaurorian:umbraingot")).key("c", item("prodigytech:circuit_crude"))
        .register()

// Crystal Cutter
crafting.remove("prodigytech:machine/automatic_crystal_cutter")
crafting.shapedBuilder()
        .mirrored()
        .name("tier5/automatic_crystal_cutter")
        .output(item("prodigytech:automatic_crystal_cutter"))
        .matrix(" E ", "FCF", "RGR")
        .key("C", item("gateway:ferramic_machine_frame")).key("F", item("essentialcraft:genitem", 9))
        .key("G", item("prodigytech:circuit_refined")).key("R", ore("ingotLead")).key("E", ore("gearEmerald"))
        .register()

// Fuel Reprocessor
crafting.remove("prodigytech:machine/fuel_processor")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/fuel_processor")
        .output(item("prodigytech:fuel_processor"))
        .matrix(" Ac", "RCR")
        .key("C", item("gateway:ferramic_machine_frame")).key("R", ore("ingotGold"))
        .key("A", item("immersiveengineering:stone_decoration", 3)).key("c", item("prodigytech:circuit_crude"))
        .register()

// Food Enricher
crafting.remove("prodigytech:machine/food_enricher")
crafting.shapedBuilder()
        .mirrored()
        .name("tier5/food_enricher")
        .output(item("prodigytech:food_enricher"))
        .matrix(" R ", "PCP", "GcG")
        .key("C", item("gateway:ferramic_machine_frame")).key("P", item("prodigytech:primordium"))
        .key("c", item("prodigytech:circuit_refined")).key("G", ore("gearFerramic")).key("R", item("embers:focal_lens"))
        .register()

// Primordial Reactor
crafting.remove("prodigytech:machine/primordialis_reactor")
crafting.shapedBuilder()
        .mirrored()
        .name("tier5/primordialis_reactor")
        .output(item("prodigytech:primordialis_reactor"))
        .matrix(" F ", "FCF", "WGW")
        .key("C", item("gateway:ferramic_machine_frame")).key("F", item("prodigytech:carbon_plate"))
        .key("G", item("prodigytech:circuit_refined")).key("W", item("essentialcraft:genitem", 6))
        .register()

// Magnetic Reassembler
crafting.remove("prodigytech:machine/magnetic_reassembler")
crafting.shapedBuilder()
        .mirrored()
        .name("tier3/magnetic_reassembler")
        .output(item("prodigytech:magnetic_reassembler"))
        .matrix(" Ac", "RCR")
        .key("C", item("gateway:ferramic_machine_frame")).key("R", ore("gearNickel")).key("A", ore("ingotCerulean")).key("c", item("prodigytech:circuit_crude"))
        .register()

// Atomic Reshaper
crafting.remove("prodigytech:machine/atomic_reshaper")
crafting.shapedBuilder()
        .mirrored()
        .name("tier5/atomic_reshaper")
        .output(item("prodigytech:atomic_reshaper"))
        .matrix(" N ", "FCF", "WGW")
        .key("C", item("gateway:ferramic_machine_frame")).key("F", item("prodigytech:carbon_plate"))
        .key("G", item("prodigytech:circuit_refined")).key("W", item("essentialcraft:genitem", 6)).key("N", item("thaumictinkerer:energetic_nitor"))
        .register()
