// Screen Controller
crafting.remove("rftools:screen_controller")
crafting.shapedBuilder()
    .name("tier3/rftools/screen_controller")
    .mirrored()
    .matrix("RCR", "GFS", "RGR")
    .key("S", item("rftools:screen"))
    .key("C", item("prodigytech:inferno_crystal"))
    .key("R", item("minecraft:redstone"))
    .key("G", ore("blockGlassColorless"))
    .key("F", item("thermalexpansion:frame", 64))
    .output(item("rftools:screen_controller"))
    .register()

// Power Relay
crafting.remove("rftools:relay")
crafting.shapedBuilder()
    .name("tier3/rftools/relay")
    .matrix("GTG", "GFG", "GTG")
    .key("F", item("thermalexpansion:frame", 64))
    .key("G", ore("ingotGold"))
    .key("T", item("minecraft:repeater"))
    .output(item("rftools:relay"))
    .register()

// Liquid Monitor
crafting.remove("rftools:liquid_monitor")
crafting.shapedBuilder()
    .name("tier3/rftools/liquid_monitor")
    .matrix(" T ", "GFG", " T ")
    .key("F", item("thermalexpansion:frame", 64))
    .key("G", item("minecraft:bucket"))
    .key("T", item("minecraft:repeater"))
    .output(item("rftools:liquid_monitor"))
    .register()

// Elevator
crafting.remove("rftools:elevator")
crafting.shapedBuilder()
    .name("tier3/rftools/elevator")
    .matrix("RPR", "RFR", "RTR")
    .key("R", item("minecraft:redstone"))
    .key("F", item("thermalexpansion:frame", 64))
    .key("P", item("prodigytech:inferno_crystal"))
    .key("T", item("minecraft:repeater"))
    .output(item("rftools:liquid_monitor"))
    .register()
