// Pyre
crafting.remove("roots:pyre")
crafting.shapedBuilder()
        .name("tier1/pyre")
        .output(item("roots:pyre"))
        .matrix(" L ", "LCL", "SMS")
        .key("L", ore("logWood")).key("C", ore("fuelCoke")).key("S", ore("cobblestone")).key("M", item("roots:terra_moss"))
        .register()

// Grove Stone
crafting.remove("roots:grove_stone")
crafting.shapedBuilder()
    .name("tier2/roots_grove_stone")
    .mirrored()
    .output(item("roots:grove_stone"))
    .matrix(" Q ", "WQT", "SGS")
    .key("S", item("mysticalworld:charred_slab"))
    .key("Q", item("minecraft:quartz_block", 2))
    .key("G", item("naturesaura:gold_brick"))
    .key("W", item("roots:wildroot"))
    .key("T", item("roots:terra_moss"))
    .register()

// Fey Crafting
crafting.remove("roots:fey_crafter")
crafting.shapedBuilder()
    .name("tier2/fey_crafter")
    .mirrored()
    .output(item("roots:fey_crafter"))
    .matrix("S S", "WJT", "SLS")
    .key("S", ore("treeSapling"))
    .key("L", ore("logWood"))
    .key("J", item("naturesaura:token_joy"))
    .key("W", item("roots:wildroot"))
    .key("T", item("roots:terra_moss"))
    .register()

mods.roots.rituals.recipeBuilder()
    .ritual(ritual("grove_supplication"))
    .input(item("theaurorian:aurorianiteingot"), ore("doorWood"), item("minecraft:mossy_cobblestone"),
           item("naturesaura:aura_bottle").withNbt(["stored_type": "naturesaura:other"]), item("roots:petals"))
    .register()
