name: Build Curseforge pack

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: build
        run: python compile.py
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curseforge-build
          path: |
            build/dimension-gateway*-normal.zip
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curseforge-build-dev
          path: |
            build/dimension-gateway*-dev.zip
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/dimension-gateway*.zip
