name: Build Curseforge pack

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build
        run: python compile.py
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curseforge-build
          path: |
            build/dimension-gateway*.zip
