content.createItem("resonating_gem").register()
content.createItem("impure_resonating_gem").register()
content.createItem("starsteel_ingot").register()
content.createItem("incomplete_runic_plate").register()
content.createItem("runic_plate").register()
